# 20240409筆記

## 練習 01

延伸 20240326 的練習02，請寫一個迴圈，問使用者十題 99 乘法的數學題，並統計使用者答對的題數。

In [2]:
import random

In [3]:
m = random.randint(2, 9)
n = random.randint(2, 9)
x = input(f"請問 {m} x {n} = ？")
if int(x)==m*n:
    print(f"沒錯，答案是 {x}!")
else:
    print(f"錯了，答案是 {m*n}!")

請問 7 x 6 = ？ 42


沒錯，答案是 42!


In [6]:
c = 0
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        print(f"沒錯，答案是 {x}!")
    else:
        print(f"錯了，答案是 {m*n}!")
print(f"總共答對{c}題！")

請問 7 x 8 = ？ 56


沒錯，答案是 56!


請問 5 x 9 = ？ 45


沒錯，答案是 45!


請問 7 x 9 = ？ 63


沒錯，答案是 63!


請問 6 x 3 = ？ 16


錯了，答案是 18!


請問 8 x 8 = ？ 64


沒錯，答案是 64!
總共答對4題！


## 練習 02

延伸練習 01，請記錄下哪些題目答對，那些題目答錯。

In [11]:
c = 0
questions = []
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        questions.append((m, n, True))
    else:
        questions.append((m, n, False))
print(f"總共答對{c}題！")
print(f"答題狀況：{questions}")

請問 7 x 8 = ？ 56
請問 8 x 7 = ？ 56
請問 7 x 7 = ？ 49
請問 7 x 8 = ？ 54
請問 6 x 2 = ？ 12


總共答對4題！
答題狀況：[(7, 8, True), (8, 7, True), (7, 7, True), (7, 8, False), (6, 2, True)]


In [7]:
questions = []

In [9]:
questions.append((3, 3, True))

In [10]:
questions

[(3, 3, True)]

## Comprehensions

In [12]:
s = '1634'

In [21]:
p = len(s)

In [15]:
for i in s:
    print(i, "==>", type(i))

1 ==> <class 'str'>
6 ==> <class 'str'>
3 ==> <class 'str'>
4 ==> <class 'str'>


In [17]:
list(s)

['1', '6', '3', '4']

In [18]:
[int(i) for i in s]

[1, 6, 3, 4]

In [19]:
x = [int(i) for i in s]

In [20]:
x

[1, 6, 3, 4]

In [23]:
y = [i**p for i in x]

In [24]:
sum(y)

1634

In [25]:
s = 'aabccdddddeeeeeffff'

In [26]:
s.count('a')

2

In [27]:
{i:s.count(i) for i in s}

{'a': 2, 'b': 1, 'c': 2, 'd': 5, 'e': 5, 'f': 4}

In [28]:
x

[1, 6, 3, 4]

In [33]:
z = (i for i in x)

In [34]:
type(z)

generator

In [35]:
for i in z:
    print(i)

1
6
3
4


In [36]:
for i in z:
    print(i)

In [37]:
z = (i for i in x)

In [39]:
next(z)

6

In [40]:
list(z)

[3, 4]

## 物件導向程式設計(OOP)簡介

* Object Oriented Programming

* class v.s., object
* member variables (data, attributes) v.s. member functions (methods)

In [41]:
type(x)

list

In [42]:
x

[1, 6, 3, 4]

In [43]:
s

'aabccdddddeeeeeffff'

In [44]:
type(s)

str

In [45]:
s.upper()

'AABCCDDDDDEEEEEFFFF'

In [46]:
class Sprite:
    pass

In [47]:
k = Sprite()

In [48]:
type(k)

__main__.Sprite

## 複習資料分析

* NumPy
* MatPlotLib
* Pandas

載入慣用法：
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [49]:
import numpy as np

In [50]:
x = [1, 2, 3]
y = [4, 5, 6]

In [52]:
list(zip(x, y))

[(1, 4), (2, 5), (3, 6)]

In [53]:
for i, j in zip(x, y):
    print(i, j)

1 4
2 5
3 6


In [54]:
z = []
for i, j in zip(x, y):
    z.append(i+j)

In [55]:
z

[5, 7, 9]

In [56]:
[i+j for i, j in zip(x, y)]

[5, 7, 9]

In [57]:
A = np.arange(25)

In [58]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
B = A.reshape(5, 5)

In [61]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
B[2, 2]

12

In [64]:
B[2]

array([10, 11, 12, 13, 14])

In [66]:
B[2, :]

array([10, 11, 12, 13, 14])

In [65]:
B[:, 2]

array([ 2,  7, 12, 17, 22])

In [67]:
B[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [69]:
B[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [70]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
B > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [73]:
B[B>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
np.where(B>12, B, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])