# 20240409筆記

## 練習 01

延伸 20240326 的練習02，請寫一個迴圈，問使用者十題 99 乘法的數學題，並統計使用者答對的題數。

In [2]:
import random

In [3]:
m = random.randint(2, 9)
n = random.randint(2, 9)
x = input(f"請問 {m} x {n} = ？")
if int(x)==m*n:
    print(f"沒錯，答案是 {x}!")
else:
    print(f"錯了，答案是 {m*n}!")

請問 7 x 6 = ？ 42


沒錯，答案是 42!


In [6]:
c = 0
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        print(f"沒錯，答案是 {x}!")
    else:
        print(f"錯了，答案是 {m*n}!")
print(f"總共答對{c}題！")

請問 7 x 8 = ？ 56


沒錯，答案是 56!


請問 5 x 9 = ？ 45


沒錯，答案是 45!


請問 7 x 9 = ？ 63


沒錯，答案是 63!


請問 6 x 3 = ？ 16


錯了，答案是 18!


請問 8 x 8 = ？ 64


沒錯，答案是 64!
總共答對4題！


## 練習 02

延伸練習 01，請記錄下哪些題目答對，那些題目答錯。

In [11]:
c = 0
questions = []
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        questions.append((m, n, True))
    else:
        questions.append((m, n, False))
print(f"總共答對{c}題！")
print(f"答題狀況：{questions}")

請問 7 x 8 = ？ 56
請問 8 x 7 = ？ 56
請問 7 x 7 = ？ 49
請問 7 x 8 = ？ 54
請問 6 x 2 = ？ 12


總共答對4題！
答題狀況：[(7, 8, True), (8, 7, True), (7, 7, True), (7, 8, False), (6, 2, True)]


In [7]:
questions = []

In [9]:
questions.append((3, 3, True))

In [10]:
questions

[(3, 3, True)]

## Comprehensions

In [12]:
s = '1634'

In [21]:
p = len(s)

In [15]:
for i in s:
    print(i, "==>", type(i))

1 ==> <class 'str'>
6 ==> <class 'str'>
3 ==> <class 'str'>
4 ==> <class 'str'>


In [17]:
list(s)

['1', '6', '3', '4']

In [18]:
[int(i) for i in s]

[1, 6, 3, 4]

In [19]:
x = [int(i) for i in s]

In [20]:
x

[1, 6, 3, 4]

In [23]:
y = [i**p for i in x]

In [24]:
sum(y)

1634

In [25]:
s = 'aabccdddddeeeeeffff'

In [26]:
s.count('a')

2

In [27]:
{i:s.count(i) for i in s}

{'a': 2, 'b': 1, 'c': 2, 'd': 5, 'e': 5, 'f': 4}

In [28]:
x

[1, 6, 3, 4]

In [33]:
z = (i for i in x)

In [34]:
type(z)

generator

In [35]:
for i in z:
    print(i)

1
6
3
4


In [36]:
for i in z:
    print(i)

In [37]:
z = (i for i in x)

In [39]:
next(z)

6

In [40]:
list(z)

[3, 4]

## 物件導向程式設計(OOP)簡介

* Object Oriented Programming

* class v.s., object
* member variables (data, attributes) v.s. member functions (methods)

In [41]:
type(x)

list

In [42]:
x

[1, 6, 3, 4]

In [43]:
s

'aabccdddddeeeeeffff'

In [44]:
type(s)

str

In [45]:
s.upper()

'AABCCDDDDDEEEEEFFFF'

In [46]:
class Sprite:
    pass

In [47]:
k = Sprite()

In [48]:
type(k)

__main__.Sprite

## 複習資料分析

* NumPy
* MatPlotLib
* Pandas

載入慣用法：
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [49]:
import numpy as np

In [50]:
x = [1, 2, 3]
y = [4, 5, 6]

In [52]:
list(zip(x, y))

[(1, 4), (2, 5), (3, 6)]

In [53]:
for i, j in zip(x, y):
    print(i, j)

1 4
2 5
3 6


In [54]:
z = []
for i, j in zip(x, y):
    z.append(i+j)

In [55]:
z

[5, 7, 9]

In [56]:
[i+j for i, j in zip(x, y)]

[5, 7, 9]

In [57]:
A = np.arange(25)

In [58]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
B = A.reshape(5, 5)

In [61]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
B[2, 2]

12

In [64]:
B[2]

array([10, 11, 12, 13, 14])

In [66]:
B[2, :]

array([10, 11, 12, 13, 14])

In [65]:
B[:, 2]

array([ 2,  7, 12, 17, 22])

In [67]:
B[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [69]:
B[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [70]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
B > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [73]:
B[B>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
np.where(B>12, B, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 鐵達尼號生存分析

In [76]:
import pandas as pd

### 讀取資料

In [111]:
train = pd.read_csv("titanic/train.csv")

In [112]:
test = pd.read_csv("titanic/test.csv")

### 檢視資料

In [113]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [114]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [115]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


### 選擇欄位(特徵值)

In [116]:
selected_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex', 'Embarked']

In [117]:
X_train = train[selected_features]

In [118]:
y_train = train['Survived']

In [119]:
X_test = test[selected_features]

In [120]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Age       714 non-null    float64
 2   SibSp     891 non-null    int64  
 3   Parch     891 non-null    int64  
 4   Fare      891 non-null    float64
 5   Sex       891 non-null    object 
 6   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [121]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Age       332 non-null    float64
 2   SibSp     418 non-null    int64  
 3   Parch     418 non-null    int64  
 4   Fare      417 non-null    float64
 5   Sex       418 non-null    object 
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


### 缺失值處理

In [122]:
X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)
X_train['Embarked'].fillna('S', inplace=True)
X_test['Age'].fillna(X_test['Age'].mean(), inplace=True)
X_test['Fare'].fillna(X_test['Fare'].mean(), inplace=True)

C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\3505239621.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)
C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\3505239621.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)

In [123]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Age       891 non-null    float64
 2   SibSp     891 non-null    int64  
 3   Parch     891 non-null    int64  
 4   Fare      891 non-null    float64
 5   Sex       891 non-null    object 
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [124]:
X_train.head()

Pclass   Age  SibSp  Parch     Fare     Sex Embarked
0       3  22.0      1      0   7.2500    male        S
1       1  38.0      1      0  71.2833  female        C
2       3  26.0      0      0   7.9250  female        S
3       1  35.0      1      0  53.1000  female        S
4       3  35.0      0      0   8.0500    male        S

### 說明一下 One-Hot Encoding

In [92]:
d = {'color':['red', 'blue', 'green', 'blue', 'red']}

In [93]:
df = pd.DataFrame(d)

In [94]:
df

color
0    red
1   blue
2  green
3   blue
4    red

In [105]:
pd.get_dummies(df, dtype=int)

color_blue  color_green  color_red
0           0            0          1
1           1            0          0
2           0            1          0
3           1            0          0
4           0            0          1

In [97]:
pd.get_dummies(df, drop_first=True)

color_green  color_red
0        False       True
1        False      False
2         True      False
3        False      False
4        False       True

### One-Hot Encoding

In [125]:
X_train = pd.get_dummies(X_train, dtype=int)
X_test = pd.get_dummies(X_test, dtype=int)

In [126]:
X_train.head()

Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  Embarked_C  \
0       3  22.0      1      0   7.2500           0         1           0   
1       1  38.0      1      0  71.2833           1         0           1   
2       3  26.0      0      0   7.9250           1         0           0   
3       1  35.0      1      0  53.1000           1         0           0   
4       3  35.0      0      0   8.0500           0         1           0   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

### 機器學習模型訓練

In [100]:
from sklearn.svm import SVC

In [101]:
clf = SVC()

In [102]:
clf.fit(X_train, y_train)

SVC()

In [103]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,

## 用Pandas做缺失值處理

In [127]:
np.random.seed(987)
data = np.random.randint(30, 101, (10, 4))

In [128]:
data

array([[81, 71, 84, 40],
       [56, 33, 74, 48],
       [92, 44, 58, 33],
       [45, 97, 94, 56],
       [84, 61, 91, 63],
       [56, 49, 80, 64],
       [40, 89, 97, 71],
       [33, 32, 76, 67],
       [64, 65, 99, 95],
       [78, 75, 95, 49]])

In [136]:
df = pd.DataFrame(data)

In [137]:
df.columns = ['國文','英文','數學','理化']

In [138]:
df.index = ["陳志忠", "洪義恬", "許家恬", "陳怡如", "劉建志", 
            "喬東蕙", "蔡孟航", "吳柏其", "潘修剛", "郭淑慧"]

In [139]:
df

國文  英文  數學  理化
陳志忠  81  71  84  40
洪義恬  56  33  74  48
許家恬  92  44  58  33
陳怡如  45  97  94  56
劉建志  84  61  91  63
喬東蕙  56  49  80  64
蔡孟航  40  89  97  71
吳柏其  33  32  76  67
潘修剛  64  65  99  95
郭淑慧  78  75  95  49

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 陳志忠 to 郭淑慧
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      10 non-null     int32
 1   英文      10 non-null     int32
 2   數學      10 non-null     int32
 3   理化      10 non-null     int32
dtypes: int32(4)
memory usage: 240.0+ bytes


In [141]:
df.loc['許家恬', '英文'] = np.nan

In [142]:
df

國文    英文  數學  理化
陳志忠  81  71.0  84  40
洪義恬  56  33.0  74  48
許家恬  92   NaN  58  33
陳怡如  45  97.0  94  56
劉建志  84  61.0  91  63
喬東蕙  56  49.0  80  64
蔡孟航  40  89.0  97  71
吳柏其  33  32.0  76  67
潘修剛  64  65.0  99  95
郭淑慧  78  75.0  95  49

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 陳志忠 to 郭淑慧
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   國文      10 non-null     int32  
 1   英文      9 non-null      float64
 2   數學      10 non-null     int32  
 3   理化      10 non-null     int32  
dtypes: float64(1), int32(3)
memory usage: 580.0+ bytes


In [145]:
df.loc['劉建志', '理化'] = np.nan
df.loc['喬東蕙', '英文'] = np.nan
df.loc['蔡孟航', '國文'] = np.nan
df.loc['吳柏其', '英文'] = np.nan
df.loc['吳柏其', '國文'] = np.nan

In [146]:
df

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   NaN  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
喬東蕙  56.0   NaN  80  64.0
蔡孟航   NaN  89.0  97  71.0
吳柏其   NaN   NaN  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 陳志忠 to 郭淑慧
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   國文      8 non-null      float64
 1   英文      7 non-null      float64
 2   數學      10 non-null     int32  
 3   理化      9 non-null      float64
dtypes: float64(3), int32(1)
memory usage: 660.0+ bytes


### dropna()

In [149]:
df.dropna()

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
陳怡如  45.0  97.0  94  56.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [150]:
df.dropna(axis=1)

數學
陳志忠  84
洪義恬  74
許家恬  58
陳怡如  94
劉建志  91
喬東蕙  80
蔡孟航  97
吳柏其  76
潘修剛  99
郭淑慧  95

In [151]:
df.dropna(how='all')

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   NaN  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
喬東蕙  56.0   NaN  80  64.0
蔡孟航   NaN  89.0  97  71.0
吳柏其   NaN   NaN  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [152]:
df.dropna(subset=['英文'])

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
蔡孟航   NaN  89.0  97  71.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [153]:
df.dropna(thresh=3)

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   NaN  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
喬東蕙  56.0   NaN  80  64.0
蔡孟航   NaN  89.0  97  71.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [154]:
df

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   NaN  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
喬東蕙  56.0   NaN  80  64.0
蔡孟航   NaN  89.0  97  71.0
吳柏其   NaN   NaN  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

### fillna()

In [155]:
df

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   NaN  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   NaN
喬東蕙  56.0   NaN  80  64.0
蔡孟航   NaN  89.0  97  71.0
吳柏其   NaN   NaN  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [156]:
df.fillna(0)

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0   0.0  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91   0.0
喬東蕙  56.0   0.0  80  64.0
蔡孟航   0.0  89.0  97  71.0
吳柏其   0.0   0.0  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [157]:
df.mean()

國文    69.500000
英文    70.142857
數學    84.800000
理化    58.111111
dtype: float64

In [158]:
df.fillna(df.mean())

國文         英文  數學         理化
陳志忠  81.0  71.000000  84  40.000000
洪義恬  56.0  33.000000  74  48.000000
許家恬  92.0  70.142857  58  33.000000
陳怡如  45.0  97.000000  94  56.000000
劉建志  84.0  61.000000  91  58.111111
喬東蕙  56.0  70.142857  80  64.000000
蔡孟航  69.5  89.000000  97  71.000000
吳柏其  69.5  70.142857  76  67.000000
潘修剛  64.0  65.000000  99  95.000000
郭淑慧  78.0  75.000000  95  49.000000

In [159]:
df.dropna(subset=['英文']).mean()

國文    68.000000
英文    70.142857
數學    90.571429
理化    59.833333
dtype: float64

In [160]:
df.fillna(df.min())

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0  33.0  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91  33.0
喬東蕙  56.0  33.0  80  64.0
蔡孟航  45.0  89.0  97  71.0
吳柏其  45.0  33.0  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [162]:
df.fillna(method='ffill')

C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0  33.0  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91  56.0
喬東蕙  56.0  61.0  80  64.0
蔡孟航  56.0  89.0  97  71.0
吳柏其  56.0  89.0  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [163]:
df.ffill()

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0  33.0  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91  56.0
喬東蕙  56.0  61.0  80  64.0
蔡孟航  56.0  89.0  97  71.0
吳柏其  56.0  89.0  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [164]:
df.bfill()

國文    英文  數學    理化
陳志忠  81.0  71.0  84  40.0
洪義恬  56.0  33.0  74  48.0
許家恬  92.0  97.0  58  33.0
陳怡如  45.0  97.0  94  56.0
劉建志  84.0  61.0  91  64.0
喬東蕙  56.0  89.0  80  64.0
蔡孟航  64.0  89.0  97  71.0
吳柏其  64.0  65.0  76  67.0
潘修剛  64.0  65.0  99  95.0
郭淑慧  78.0  75.0  95  49.0

In [166]:
df['國文']

陳志忠    81.0
洪義恬    56.0
許家恬    92.0
陳怡如    45.0
劉建志    84.0
喬東蕙    56.0
蔡孟航     NaN
吳柏其     NaN
潘修剛    64.0
郭淑慧    78.0
Name: 國文, dtype: float64

In [167]:
df[['國文', '英文']]

國文    英文
陳志忠  81.0  71.0
洪義恬  56.0  33.0
許家恬  92.0   NaN
陳怡如  45.0  97.0
劉建志  84.0  61.0
喬東蕙  56.0   NaN
蔡孟航   NaN  89.0
吳柏其   NaN   NaN
潘修剛  64.0  65.0
郭淑慧  78.0  75.0

In [168]:
columns = ['國文', '英文']
df[columns]

國文    英文
陳志忠  81.0  71.0
洪義恬  56.0  33.0
許家恬  92.0   NaN
陳怡如  45.0  97.0
劉建志  84.0  61.0
喬東蕙  56.0   NaN
蔡孟航   NaN  89.0
吳柏其   NaN   NaN
潘修剛  64.0  65.0
郭淑慧  78.0  75.0

## 分析 Scikit-learn 的 breast cancer dataset

In [169]:
from sklearn.datasets import load_breast_cancer

In [170]:
data = load_breast_cancer()

In [171]:
X = data.data

In [172]:
y = data.target

In [173]:
X[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [174]:
y[0]

0

In [175]:
X.shape

(569, 30)

In [176]:
y.shape

(569,)

In [178]:
sum(y)

357

### 分割訓練集跟測試集資料

In [179]:
from sklearn.model_selection import train_test_split

In [180]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=987)

### 使用SVM做分類

In [181]:
from sklearn.svm import SVC

In [182]:
clf = SVC()

In [183]:
clf.fit(X_train, y_train)

SVC()

In [184]:
clf.score(X_test, y_test)

0.9385964912280702

### 使用 Random Forest 來做分類

In [186]:
from sklearn.ensemble import RandomForestClassifier

In [187]:
clf = RandomForestClassifier()

In [188]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [189]:
clf.score(X_test, y_test)

0.9736842105263158

In [190]:
X_test[0]

array([1.959e+01, 1.815e+01, 1.307e+02, 1.214e+03, 1.120e-01, 1.666e-01,
       2.508e-01, 1.286e-01, 2.027e-01, 6.082e-02, 7.364e-01, 1.048e+00,
       4.792e+00, 9.707e+01, 4.057e-03, 2.277e-02, 4.029e-02, 1.303e-02,
       1.686e-02, 3.318e-03, 2.673e+01, 2.639e+01, 1.749e+02, 2.232e+03,
       1.438e-01, 3.846e-01, 6.810e-01, 2.247e-01, 3.643e-01, 9.223e-02])

In [191]:
clf.predict([X_test[0]])

array([0])

## 使用機器學習預測股市漲跌

In [192]:
import yfinance as yf

In [193]:
import requests

In [208]:
session = requests.Session()
session.verify = False
df = yf.download('2330.tw', session=session)

C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'query2.finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[*********************100%%**********************]  1 of 1 completed


In [209]:
df.head(10)

Open       High        Low      Close  Adj Close  \
Date                                                                
2000-01-04  69.649033  69.649033  68.475182  69.649033  34.502380   
2000-01-05  69.649033  71.214043  68.866341  71.214043  35.277653   
2000-01-06  70.822884  71.214043  69.649033  69.649033  34.502380   
2000-01-07  67.301331  68.475182  66.518639  67.692490  33.533154   
2000-01-10  69.649033  70.431351  68.475182  70.040192  34.696156   
2000-01-11  70.822884  71.605202  68.475182  68.866341  34.114662   
2000-01-12  69.257500  70.822884  68.866341  70.822884  35.083885   
2000-01-13  70.822884  70.822884  69.649033  69.649033  34.502380   
2000-01-14  70.431351  72.387894  70.040192  71.214043  35.277653   
2000-01-17  74.344429  74.344429  73.170578  73.170578  36.246864   

                  Volume  
Date                      
2000-01-04  200662336736  
2000-01-05  402466805912  
2000-01-06  197545715802  
2000-01-07  235270344752  
2000-01-10  276171685539  
2000-01-11  277769544650  
2000-01-12  216246806621  
2000-01-13  147490954216  
2000-01-14  288318964353  
2000-01-17  155256940719

In [210]:
df['漲跌'] = df.Close.shift(-1) - df.Close

In [211]:
df.head()

Open       High        Low      Close  Adj Close  \
Date                                                                
2000-01-04  69.649033  69.649033  68.475182  69.649033  34.502380   
2000-01-05  69.649033  71.214043  68.866341  71.214043  35.277653   
2000-01-06  70.822884  71.214043  69.649033  69.649033  34.502380   
2000-01-07  67.301331  68.475182  66.518639  67.692490  33.533154   
2000-01-10  69.649033  70.431351  68.475182  70.040192  34.696156   

                  Volume        漲跌  
Date                                
2000-01-04  200662336736  1.565010  
2000-01-05  402466805912 -1.565010  
2000-01-06  197545715802 -1.956543  
2000-01-07  235270344752  2.347702  
2000-01-10  276171685539 -1.173851

In [212]:
df['漲跌'] = df['漲跌'].map(lambda x: 1 if x>=0 else 0)

In [213]:
df.head()

Open       High        Low      Close  Adj Close  \
Date                                                                
2000-01-04  69.649033  69.649033  68.475182  69.649033  34.502380   
2000-01-05  69.649033  71.214043  68.866341  71.214043  35.277653   
2000-01-06  70.822884  71.214043  69.649033  69.649033  34.502380   
2000-01-07  67.301331  68.475182  66.518639  67.692490  33.533154   
2000-01-10  69.649033  70.431351  68.475182  70.040192  34.696156   

                  Volume  漲跌  
Date                          
2000-01-04  200662336736   1  
2000-01-05  402466805912   0  
2000-01-06  197545715802   0  
2000-01-07  235270344752   1  
2000-01-10  276171685539   0

In [214]:
df.tail()

Open   High    Low  Close  Adj Close    Volume  漲跌
Date                                                           
2024-04-01  783.0  783.0  769.0  770.0      770.0  21041261   1
2024-04-02  784.0  790.0  783.0  790.0      790.0  37974481   0
2024-04-03  783.0  785.0  778.0  780.0      780.0  30890544   1
2024-04-08  789.0  792.0  783.0  783.0      783.0  32202226   1
2024-04-09  795.0  820.0  792.0  819.0      819.0  59583742   0

In [215]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', '漲跌'], dtype='object')

In [216]:
df.columns[:-1]

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [217]:
X = df[df.columns[:-1]]

In [218]:
y = df['漲跌']

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=987)

In [221]:
from sklearn.svm import SVC

In [222]:
clf = SVC()

In [223]:
clf.fit(X_train, y_train)

SVC()

In [224]:
clf.score(X_test, y_test)

0.5421487603305785

In [235]:
session = requests.Session()
session.verify = False
df = yf.download('2330.tw', session=session)

C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'query2.finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[*********************100%%**********************]  1 of 1 completed


In [238]:
df['5MA'] = df.Close.rolling(window=5).mean()
df['10MA'] = df.Close.rolling(window=10).mean()
df['20MA'] = df.Close.rolling(window=20).mean()
df['60MA'] = df.Close.rolling(window=60).mean()
df['120MA'] = df.Close.rolling(window=120).mean()

In [239]:
df.head(10)

Open       High        Low      Close  Adj Close  \
Date                                                                
2000-01-04  69.649033  69.649033  68.475182  69.649033  34.502384   
2000-01-05  69.649033  71.214043  68.866341  71.214043  35.277653   
2000-01-06  70.822884  71.214043  69.649033  69.649033  34.502384   
2000-01-07  67.301331  68.475182  66.518639  67.692490  33.533157   
2000-01-10  69.649033  70.431351  68.475182  70.040192  34.696156   
2000-01-11  70.822884  71.605202  68.475182  68.866341  34.114651   
2000-01-12  69.257500  70.822884  68.866341  70.822884  35.083881   
2000-01-13  70.822884  70.822884  69.649033  69.649033  34.502384   
2000-01-14  70.431351  72.387894  70.040192  71.214043  35.277653   
2000-01-17  74.344429  74.344429  73.170578  73.170578  36.246876   

                  Volume        5MA       10MA  20MA  60MA  120MA  
Date                                                               
2000-01-04  200662336736        NaN        NaN   NaN   NaN    NaN  
2000-01-05  402466805912        NaN        NaN   NaN   NaN    NaN  
2000-01-06  197545715802        NaN        NaN   NaN   NaN    NaN  
2000-01-07  235270344752        NaN        NaN   NaN   NaN    NaN  
2000-01-10  276171685539  69.648958        NaN   NaN   NaN    NaN  
2000-01-11  277769544650  69.492419        NaN   NaN   NaN    NaN  
2000-01-12  216246806621  69.414188        NaN   NaN   NaN    NaN  
2000-01-13  147490954216  69.414188        NaN   NaN   NaN    NaN  
2000-01-14  288318964353  70.118498        NaN   NaN   NaN    NaN  
2000-01-17  155256940719  70.744576  70.196767   NaN   NaN    NaN

In [241]:
df = df.dropna()

In [247]:
df['漲跌'] = df.Close.shift(-7) - df.Close
df = df.dropna()
df['漲跌'] = df['漲跌'].map(lambda x: 1 if x>=0 else -1)
X = df[df.columns[:-1]]
y = df['漲跌']
df.head()

C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\4081553362.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['漲跌'] = df.Close.shift(-7) - df.Close


Open       High        Low      Close  Adj Close  \
Date                                                                
2000-06-19  74.876274  75.126854  73.373741  74.125008  36.719666   
2000-06-20  75.627533  75.627533  74.125008  74.375587  36.843800   
2000-06-21  74.375587  74.626167  73.624329  73.624329  36.471649   
2000-06-22  73.123642  74.876274  73.123642  74.626167  36.967934   
2000-06-23  74.125008  74.375587  73.123642  73.123642  36.223610   

                 Volume        5MA       10MA       20MA       60MA  \
Date                                                                  
2000-06-19  57780102371  75.828000  77.530896  76.491656  76.283521   
2000-06-20  45751547817  75.176872  77.055080  76.378967  76.160136   
2000-06-21  37673562283  74.475726  76.353885  76.341404  76.056833   
2000-06-22  64192016747  74.375589  75.953242  76.429059  75.944144   
2000-06-23  49329023488  73.974947  75.352232  76.441588  75.825976   

                120MA  漲跌  
Date                       
2000-06-19  76.412788  -1  
2000-06-20  76.452176  -1  
2000-06-21  76.472262  -1  
2000-06-22  76.513738  -1  
2000-06-23  76.558997  -1

In [248]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=987)
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5548986486486487