# 20240409筆記

## 練習 01

延伸 20240326 的練習02，請寫一個迴圈，問使用者十題 99 乘法的數學題，並統計使用者答對的題數。

In [2]:
import random

In [3]:
m = random.randint(2, 9)
n = random.randint(2, 9)
x = input(f"請問 {m} x {n} = ？")
if int(x)==m*n:
    print(f"沒錯，答案是 {x}!")
else:
    print(f"錯了，答案是 {m*n}!")

請問 7 x 6 = ？ 42


沒錯，答案是 42!


In [6]:
c = 0
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        print(f"沒錯，答案是 {x}!")
    else:
        print(f"錯了，答案是 {m*n}!")
print(f"總共答對{c}題！")

請問 7 x 8 = ？ 56


沒錯，答案是 56!


請問 5 x 9 = ？ 45


沒錯，答案是 45!


請問 7 x 9 = ？ 63


沒錯，答案是 63!


請問 6 x 3 = ？ 16


錯了，答案是 18!


請問 8 x 8 = ？ 64


沒錯，答案是 64!
總共答對4題！


## 練習 02

延伸練習 01，請記錄下哪些題目答對，那些題目答錯。

In [11]:
c = 0
questions = []
for i in range(5):
    m = random.randint(2, 9)
    n = random.randint(2, 9)
    x = input(f"請問 {m} x {n} = ？")
    if int(x)==m*n:
        c += 1
        questions.append((m, n, True))
    else:
        questions.append((m, n, False))
print(f"總共答對{c}題！")
print(f"答題狀況：{questions}")

請問 7 x 8 = ？ 56
請問 8 x 7 = ？ 56
請問 7 x 7 = ？ 49
請問 7 x 8 = ？ 54
請問 6 x 2 = ？ 12


總共答對4題！
答題狀況：[(7, 8, True), (8, 7, True), (7, 7, True), (7, 8, False), (6, 2, True)]


In [7]:
questions = []

In [9]:
questions.append((3, 3, True))

In [10]:
questions

[(3, 3, True)]

## Comprehensions

In [12]:
s = '1634'

In [21]:
p = len(s)

In [15]:
for i in s:
    print(i, "==>", type(i))

1 ==> <class 'str'>
6 ==> <class 'str'>
3 ==> <class 'str'>
4 ==> <class 'str'>


In [17]:
list(s)

['1', '6', '3', '4']

In [18]:
[int(i) for i in s]

[1, 6, 3, 4]

In [19]:
x = [int(i) for i in s]

In [20]:
x

[1, 6, 3, 4]

In [23]:
y = [i**p for i in x]

In [24]:
sum(y)

1634

In [25]:
s = 'aabccdddddeeeeeffff'

In [26]:
s.count('a')

2

In [27]:
{i:s.count(i) for i in s}

{'a': 2, 'b': 1, 'c': 2, 'd': 5, 'e': 5, 'f': 4}

In [28]:
x

[1, 6, 3, 4]

In [33]:
z = (i for i in x)

In [34]:
type(z)

generator

In [35]:
for i in z:
    print(i)

1
6
3
4


In [36]:
for i in z:
    print(i)

In [37]:
z = (i for i in x)

In [39]:
next(z)

6

In [40]:
list(z)

[3, 4]

## 物件導向程式設計(OOP)簡介

* Object Oriented Programming

* class v.s., object
* member variables (data, attributes) v.s. member functions (methods)

In [41]:
type(x)

list

In [42]:
x

[1, 6, 3, 4]

In [43]:
s

'aabccdddddeeeeeffff'

In [44]:
type(s)

str

In [45]:
s.upper()

'AABCCDDDDDEEEEEFFFF'

In [46]:
class Sprite:
    pass

In [47]:
k = Sprite()

In [48]:
type(k)

__main__.Sprite

## 複習資料分析

* NumPy
* MatPlotLib
* Pandas

載入慣用法：
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [49]:
import numpy as np

In [50]:
x = [1, 2, 3]
y = [4, 5, 6]

In [52]:
list(zip(x, y))

[(1, 4), (2, 5), (3, 6)]

In [53]:
for i, j in zip(x, y):
    print(i, j)

1 4
2 5
3 6


In [54]:
z = []
for i, j in zip(x, y):
    z.append(i+j)

In [55]:
z

[5, 7, 9]

In [56]:
[i+j for i, j in zip(x, y)]

[5, 7, 9]

In [57]:
A = np.arange(25)

In [58]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
B = A.reshape(5, 5)

In [61]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
B[2, 2]

12

In [64]:
B[2]

array([10, 11, 12, 13, 14])

In [66]:
B[2, :]

array([10, 11, 12, 13, 14])

In [65]:
B[:, 2]

array([ 2,  7, 12, 17, 22])

In [67]:
B[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [69]:
B[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [70]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
B > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [73]:
B[B>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
np.where(B>12, B, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 鐵達尼號生存分析

In [76]:
import pandas as pd

In [77]:
train = pd.read_csv("titanic/train.csv")

In [78]:
test = pd.read_csv("titanic/test.csv")

In [80]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [79]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [81]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [82]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [83]:
selected_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex', 'Embarked']

In [84]:
X_train = train[selected_features]

In [85]:
y_train = train['Survived']

In [86]:
X_test = test[selected_features]

In [87]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Age       714 non-null    float64
 2   SibSp     891 non-null    int64  
 3   Parch     891 non-null    int64  
 4   Fare      891 non-null    float64
 5   Sex       891 non-null    object 
 6   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [88]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Age       332 non-null    float64
 2   SibSp     418 non-null    int64  
 3   Parch     418 non-null    int64  
 4   Fare      417 non-null    float64
 5   Sex       418 non-null    object 
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [89]:
X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)
X_train['Embarked'].fillna('S', inplace=True)
X_test['Age'].fillna(X_test['Age'].mean(), inplace=True)
X_test['Fare'].fillna(X_test['Fare'].mean(), inplace=True)

C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\3505239621.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)
C:\Users\Victor\AppData\Local\Temp\ipykernel_14832\3505239621.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)

In [90]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Age       891 non-null    float64
 2   SibSp     891 non-null    int64  
 3   Parch     891 non-null    int64  
 4   Fare      891 non-null    float64
 5   Sex       891 non-null    object 
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [91]:
X_train.head()

Pclass   Age  SibSp  Parch     Fare     Sex Embarked
0       3  22.0      1      0   7.2500    male        S
1       1  38.0      1      0  71.2833  female        C
2       3  26.0      0      0   7.9250  female        S
3       1  35.0      1      0  53.1000  female        S
4       3  35.0      0      0   8.0500    male        S

In [92]:
d = {'color':['red', 'blue', 'green', 'blue', 'red']}

In [93]:
df = pd.DataFrame(d)

In [94]:
df

color
0    red
1   blue
2  green
3   blue
4    red

In [95]:
pd.get_dummies(df)

color_blue  color_green  color_red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False
4       False        False       True

In [97]:
pd.get_dummies(df, drop_first=True)

color_green  color_red
0        False       True
1        False      False
2         True      False
3        False      False
4        False       True

In [99]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)